CART=MBC5+RAM+BATTERY
# RAMSIZE 2: 64 KBit
RAMSIZE=2
ROMVER=0
TITLE=BYOTHEMESAD
LICENSEE=QQ
MFRCODE=QNVR

# ROMSIZE 3: 2 MBit
# Not used as an actual parameter!
ROMSIZE=3

PAD_VALUE=0xFF

ASFLAGS=(-p ${PAD_VALUE} -DBUILD_CART=${CART} -DBUILD_RAMSIZE=${RAMSIZE} -DBUILD_ROMSIZE=${ROMSIZE} -Iinc/ -Isrc/ -Iout/ -Wall -Wextra)
LDFLAGS=(-S romx=127,wramx=7)
#LDFLAGS=()
FIXFLAGS=(-C -m ${CART} -r ${RAMSIZE} -n ${ROMVER} -t ${TITLE} -k ${LICENSEE} -i ${MFRCODE} -p ${PAD_VALUE} -v)

